const testimoniosData = [
  // Menores
  { icon: "🧒", name: "1. Simón Antonio Riquelo", info: "Edad: bebé | Situación: desaparecido / apropiado", text: '"El 13 de julio de 1976 (...) me encontraba terminándole de dar el pecho a mi hijo Simón. Forzaron la puerta (...) comenzaron a torturarme (...) Cuando me sacaron de la casa les pregunté qué iba a ocurrir con el niño. Me respondieron que no debía preocuparme, que el niño se iba a quedar con ellos (...) Esa fue la última vez que vi a Simón." - Testimonio (madre)' },
  { icon: "🧒", name: "2. Griselda (13 años) y bebé Viviana", info: "Situación: abandono durante operativo", text: '"Optaron por llevarnos a todos, menos a Viviana, de seis meses de edad, que junto con Griselda, mi hermana de 13 años, quedaron en el domicilio."' },
  { icon: "🧒", name: "3. Hijos de Norberto Liwsky", info: "Edad: menores | Situación: secuestro familiar", text: '"Mi esposa y mis dos hijas ya habían sido capturadas y \'chupadas\'." - Testimonio (padre)' },
  { icon: "🧒", name: "4. Hijo de María Teresa de Cuello", info: "Situación: testigo directo de secuestro", text: '"El 26 de noviembre de 1976 a la madrugada invadieron nuestra vivienda (...) preguntaron quién era Teresa (...) la secuestraron (...) cuando mi padre intentó oponerse, le partieron la cabeza de un culatazo." - Testimonio (hijo)' },
  { icon: "🧒", name: "5. Niños en Hospital de Campo de Mayo", info: "Edades: 2, 3 y 5 años | Situación: niños retenidos en ámbito militar", text: '"Vi a niños pequeños (...) dos chiquitos de 3 y 5 años (...) otra vez una criatura de aproximadamente 2 años, que lloraba pidiendo a su madre (...) al pasar algunas horas más tarde (...) los chicos ya no estaban." - Testimonio (médico)' },
  { icon: "🧒", name: "6. Menores apropiadas", info: "Situación: apropiación y adopción ilegal", text: '"El Tribunal procedió entonces a entregar a las menores en guarda provisoria (...) un año después (...) obtuvo la adopción plena." - Testimonio institucional' },
  { icon: "🧒", name: "7. Niños en centros clandestinos", info: "Situación: tortura / exposición", text: '"Presenciaban las torturas a que eran sometidos sus padres, o eran ellos mismos torturados en presencia de éstos." - Testimonio general' },
  { icon: "🧒", name: "8. Niños durante secuestros domiciliarios", info: "Edad: 5 años", text: '"Le dijeron al nene que cerrara los ojos."' },

  // Embarazadas y violencia a mujeres
  { icon: "🤰", name: "1. Mujer embarazada en cautiverio", info: "Situación: embarazo dentro de centro clandestino", text: '"Había una chica embarazada (...) estaba muy avanzada (...) la mantenían en las mismas condiciones que a todos (...) atada, vendada (...) se quejaba mucho por los dolores." - Testimonio de sobreviviente' },
  { icon: "🤰", name: "2. Parto en cautiverio", info: "Situación: nacimiento dentro de centro clandestino", text: '"Una detenida dio a luz en el lugar (...) no había ningún tipo de atención médica adecuada (...) después del nacimiento, el bebé fue separado de la madre."' },
  { icon: "🤰", name: "3. Embarazada desaparecida", info: "Situación: secuestro estando embarazada", text: '"Se encontraba embarazada al momento de su detención (...) fue vista en el centro clandestino (...) luego no se volvió a saber ni de ella ni del hijo."' },
  { icon: "🤰", name: "4. Testimonio sobre mujeres embarazadas en centros", info: "Situación: patrón sistemático", text: '"Las embarazadas eran mantenidas con vida hasta el momento del parto (...) luego se apropiaban de los niños."' },
  { icon: "👩", name: "5. Testimonio de mujer detenida", info: "Situación: violencia extrema", text: '"Fui secuestrada en mi casa (...) me golpearon (...) me aplicaron picana eléctrica (...) permanecí vendada todo el tiempo."' },
  { icon: "👨", name: "6. Sobreviviente", info: "Situación: tortura sistemática", text: '"Me desnudaron (...) me ataron a una cama metálica (...) comenzaron a pasarme corriente eléctrica por todo el cuerpo."' },
  { icon: "👩👧", name: "7. Madre separada de su hijo", info: "Situación: dolor de una madre", text: '"Escuchaba a mi hijo llorar (...) no me dejaban verlo (...) no supe más de él."' },
  { icon: "👨", name: "8. Secuestro con violencia extrema", info: "Situación: operativo nocturno", text: '"Entraron de noche (...) rompieron todo (...) me tiraron al piso (...) me llevaron encapuchado."' },
  { icon: "👩", name: "9. Detenida", info: "Situación: aislamiento total", text: '"No sabía si era de día o de noche (...) estaba siempre vendada (...) los gritos eran constantes."' },
  { icon: "👨👩👧", name: "10. Familia completa secuestrada", info: "Situación: desmembramiento familiar", text: '"Nos llevaron a todos (...) nos separaron (...) nunca más volví a ver a algunos de ellos."' },

  // Mas testimonios
  { icon: "👨", name: "1. Juan de Dios Gómez", info: "Situación: detenido-desaparecido", text: '"El 10 de agosto de 1976 (...) detuvieron a mi hijo Juan de Dios Gómez (...) Después se fueron con mi hijo y no tuvimos más noticias de él." - Testimonio (madre)' },
  { icon: "👨", name: "3. Norberto Liwsky", info: "Situación: secuestro familiar", text: '"Mi esposa y mis dos hijas ya habían sido capturadas y \'chupadas\'."' },
  { icon: "👨", name: "4. Alberto Santiago Bumichon", info: "Situación: secuestro y asesinato", text: '"Mi esposo, mi hijo David y yo fuimos secuestrados (...) Mi hijo fue liberado (...) El cadáver de mi esposo fue hallado con siete impactos de bala en la garganta." - Testimonio (esposa)' },
  { icon: "👩", name: "5. Graciela Mabel Barroca", info: "Situación: estudiante desaparecida", text: '"Mi otra hija (...) regresó (...) ya que al día siguiente tenía un examen (...) la detuvieron (...) y se la llevaron (...) sigue desaparecida." - Testimonio (madre)' },
  { icon: "👨👩👧", name: "6. Familia Núñez", info: "Situación: operativo violento + múltiples secuestros", text: '"Durante el operativo (...) no permitieron que nadie me auxiliara (...) debí permanecer en la misma posición sin comer ni ser atendida (...) amenazada de continuo." - Testimonio (familiar cuadripléjica)' },
  { icon: "👨", name: "7. Testimonio de sobreviviente", info: "Situación: tortura en centro clandestino", text: '"Fui encapuchado (...) atado (...) comenzaron a aplicarme picana eléctrica en distintas partes del cuerpo (...) los interrogatorios eran constantes."' },
  { icon: "👨", name: "8. Testimonio sobre secuestro nocturno", info: "Situación: irrupción domiciliaria", text: '"Forzaron la puerta (...) entraron violentamente (...) me golpearon (...) me encapucharon y me llevaron sin dar explicación."' },
  { icon: "👩", name: "9. Testimonio de mujer detenida", info: "Situación: detención ilegal + tortura", text: '"Fui detenida sin orden judicial (...) me mantuvieron vendada (...) escuchaba los gritos de otras personas siendo torturadas."' },
  { icon: "👨", name: "10. Testimonio sobre centros clandestinos", info: "Situación: condiciones de detención", text: '"Permanecíamos vendados (...) no sabíamos si era de día o de noche (...) los gritos eran permanentes."' }
];
